# Generated by Django 5.1.1 on 2024-10-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('training_program', '0002_alter_trainingprogram_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingprogram',
            name='subjects',
            field=models.ManyToManyField(related_name='programs', to='subject.subject'),
        ),
    ]
