# Generated by Django 5.1.1 on 2024-10-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_exercise', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('c', 'C')], default='python', max_length=10),
        ),
    ]
