# Generated by Django 5.1.1 on 2024-10-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding_exercise', '0002_delete_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='slug',
        ),
    ]
