# Generated by Django 5.0.9 on 2024-10-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprogress',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
