# Generated by Django 5.1.1 on 2024-09-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=254),
        ),
    ]
