# Generated by Django 5.0.9 on 2024-10-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_remove_material_subject_material_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='google_drive_link',
        ),
    ]
