# Generated by Django 5.0.9 on 2024-10-09 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_group', '0001_initial'),
        ('training_program', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.ManyToManyField(blank=True, related_name='assigned_users', to='module_group.module')),
                ('training_programs', models.ManyToManyField(related_name='users', to='training_program.trainingprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
