# Generated by Django 5.0.9 on 2024-10-07 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture_url', models.URLField(blank=True, max_length=10000, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('learning_style', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_language', models.CharField(blank=True, max_length=50, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
